### PR TITLE
Speech

### PR DESCRIPTION
**Pull request by gossu**
Current functionality:

Mic button appears only when browser supports google speach.
Clicking the button starts speech recognition, input field is filled while you talk and suggestions appear after. You can disable speech recognition by clicking the button again.

### CODE REVIEW

**Comment by worldsayshi** [comment]
I get js errors in console when trying to use it:
Uncaught ReferenceError: startButton is not defined
Uncaught ReferenceError: tabChanged is not defined

Have you commited all js?

_Edit:_ My fault

**Comment by gossu** [comment]
I think that everything we talked about is already implemented:
- there is a voice command to clear the input in speech mode. (say "reset")
- there is a clear button appearing when in speech mode
- search starts automatically if you say a valid phrase ( -> there is only one suggestion)

**Comment by gossu** [comment]
So potentially this is ready to be merged

**Comment by worldsayshi** [comment]
I can't get the reset command to work. Or rather, it seems to only remove parts of the text that have been recently uttered, not really clearing the entire input.

**Comment by worldsayshi** [comment]
It seems like it is extremely hard for the google api to recognize 'reset', maybe we should choose some other word or a phrase. It seems easy for it to recognize "start over".

**Comment by gossu** [comment]
How can I reproduce the problem that you have with reset not clearing everything?

As for google speech not recognizing "reset". I think it probably depends on person speaking -> it worked very well for me so I decided to use this one. If "start over" works for you I can add it as another option that clears the field. Maybe we can have even more (like "clear", "back" or  "wtf i didnt say that!")

**Pull request merged**
