### PR TITLE
Behaviors

### PR DESCRIPTION
**Pull request by gossu**
Pull request created in order to enable discussion here. This is not intended to be actually merged yet.

TODO identified by me:
- a bit more of cleanup and code reorganization
- Queries that had names written incompletely ("travel from Bli to trol") can be treated as complete queries. This should be changed.
- Words order in query is not checked when judging its completness. This should be changed. (e.g. "travel from Bli" is treated same as "Bli from travel")
- Returning two similiar names is not avoided if user specified two names that could be interpreted as same. This we might want to change (e.g "travel from trol to trol" will now end up in suggestion "Travel from Trollåsen to Trollåsen")
- some names could be marked as more important in the solr index (e.g. bigger stations, more popular programming languages) so that we suggest them in first place. But do we have any data for that?

### CODE REVIEW

**Comment by gossu** [comment]
Updating my TODO list after my recent commits:
- a bit more of cleanup and code reorganization
- some names could be marked as more important in the solr index (e.g. bigger stations, more popular programming languages) so that we suggest them in first place. But do we have any data for that?

**Comment by worldsayshi** [comment]
Here are some problematic things I see when looking at the behavior of 'precision search' completion. I'm not sure how these remarks relate to the requirements document yet:
1. "java" -> "people who know Java or Lisp", ...
   Should be: "people who know Java", ...
2. "people who know" -> "people who know Lisp", "people who know Lisp or ..."
   Should be: "people who know Lisp", "people who know <foo>", "people who know <bar>"
3. "people who know Java" -> "people who know Java or Lisp and Lisp", ...
   Should be: "people who know Java", ...
4. "people who work with Djurens Rätt or Djurens Rätt and {{Organization}}"
   Should be: Don't mind the {{Organization}}. That's [a separate issue](https://issues.findwise.com/issues/14051). However "Djurens Rätt or Djurens Rätt" is redundant.

**Comment by worldsayshi** [comment]
You should be able to debug using the GUI now. Merge the merge_refactor branch onto this one if you want to see result list as well.

**Comment by worldsayshi** [comment]
Vasttrafik:

Asking for completions on "From" gives us many grammatical variations but no variations on names. I think we should have name variation before grammatical variation. (I need to think about this. Change requirements etc.)

http://localhost:45678/api/vasttrafik/suggestSentences?q=From+Troll%C3%A4ngeN&lang=VasttrafikEngConcat

**Comment by worldsayshi** [comment]
Also: "From" -> "From Bli to Bli", ... 
(repeated names)

**Comment by gossu** [comment]
My answers:
- Names are not repeated in vasttrafik and precisionSearch if you use the norep parameter setting it to **"&norep=station"** or **"&norep=skill,location,organization"** accordingly. If you prefer i can make it default that service avoids duplicating any nametypes and instead you can specify these nametypes that should have duplicates allowed
- You can add more variations on names by ussing add parameter, e.g. **"&add=5"**
- "java" -> "people who know Java or Lisp", "people who know Java" -> "people who know Java or Lisp and Lisp" 
  Both are strange, will debug that
- {{Organization}} {{Location}} this is also sth i can try and debug

**Comment by gossu** [comment]
I consider "java" -> "people who know Java or Lisp" resolved (by fixing the nameType counts in solr index)

Also, testing with gui should now be less annoying since I changed it to use norep and add parameters (avoiding name duplicates and giving some name combinations for each rule)

**Comment by gossu** [comment]
{{Organization}} {{Location}} problem resolved -> filter queries built in solrnamesuggester were incorrect

**Comment by worldsayshi** [comment]
The SuggestionBehavior constructor could use the EnumSet trick that you used in the previous pull request. I think it would be clearer that way.

**Comment by worldsayshi** [comment]
LinkedList is used here and there. ArrayList is for most cases a better implementation (1). I'd say we should switch to that unless there is a good reason for using linkedlist.

(1) - http://stackoverflow.com/a/322742/439034

**Comment by worldsayshi** [comment]
In the while loop in createSuggestionsForLinearization there is an integer 'index'. It seems that we can just use suggestions.size()? If they are supposed to be the same I think we should just use the list size.

**Comment by gossu** [comment]
fixed everything according to your last three comments

**Comment by worldsayshi** [comment]
I don't think we will gain much by having ContinueHint as a configurable property. At least not in that way. We could remove it for now.

**Comment by worldsayshi** [comment]
No need to have an empty constructor in SuggestionParams

**Comment by worldsayshi** [comment]
If I type "Stockholm Java" in precision search gui tab I get an exception:

ServletHandler:/api/precisionSearch/suggestSentences
org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: Invalid Number: 1Location_i

**Comment by worldsayshi** [comment]
variable name diff in suggestioncomparator is a bit nondescriptive.

**Comment by worldsayshi** [comment]
I’m adding some line breaks and fixing some typos on my end. Individually they seem to minor to comment on. As a general rule - and this is mostly a personal preference - I'd like to add line breaks so that the code fits in the visible area without having to scroll horizontally, unless the code become less clear that way.

**Comment by worldsayshi** [comment]
"lowWord" - Why not lowerCaseWord ? :)

**Comment by worldsayshi** [comment]
(This is a nitpick and perhaps not needed) For this logic:
if (word.startsWith(placeholderPrefix) && word.endsWith(placeholderSuffix)) {
...
}

Maybe we could use the defTempl templating object. That way we can have all the templating logic in one place. Add method in the templating class if you need to.

**Comment by worldsayshi** [comment]
In buildSuggestion, getBestLinearization and SuggestionComparator.compare there are a lot of interesting things going on. See if there are ways to make it a bit easier to read/understand. A lot of it is probably hard to make easier but perhaps we can improve it somewhat. I'm thinking more descriptive naming - like renaming 'diff' to a name that describes what it is used for in the given context and try to avoid too many nested for loops by breaking it up into methods.  I think adding comments is a "last resort".

Also for example here:

```
                List<Interpretation> new_interpretations = new ArrayList<>();
                for (Interpretation interpretation : namesInterpretations) {
                    if (new_interpretations.size() >= maxNumOfInterpretations) {
                        break;
                    }
                    for (int i = 0; i < nameResults.size(); i++) {
                        NameResult altName = nameResults.get(i);
                        altName.setOriginalName(word);
                        ArrayList<NameResult> new_interpretation = new ArrayList<>(
                                interpretation.getNameResults());
                        new_interpretation.add(altName);
                        new_interpretations.add(new Interpretation(new_interpretation));
                    }
                }
                namesInterpretations = new_interpretations;
```

Could become 

```
                namesInterpretations = somethingSomething(...);
```

**Comment by worldsayshi** [comment]
I found something interesting: In order to avoid using JSONService.buildSuggestionParams we should be able to simply use SuggestionParams as an argument to suggestSentences. See here:

http://stackoverflow.com/a/16942352/439034

**Comment by gossu** [comment]
fixed everything related to previous comments

**Comment by worldsayshi** [comment]
'comparisionResult' doesn't really say much more than 'diff' - they are synonymous? What kind of diff is it?

**Comment by worldsayshi** [comment]
updateInterpreatations - typo

**Comment by worldsayshi** [comment]
"removed unused classes" - Yay :D

All in all (current LOC score): 
+1,155 −1,283

Nice.

**Comment by worldsayshi** [comment]
"replaced build suggestion params with one SuggestionParams parameter" - Felt good didn't it? :)

**Comment by gossu** [comment]
All previous comments covered with my latest commits :)

**Pull request merged**
