### PR TITLE
Traffic suggestions

### PR DESCRIPTION
**Pull request by gossu**

### CODE REVIEW

**Comment by worldsayshi** [comment]
Remove "To change this template ..."

**Comment by worldsayshi** [comment]
This seems quite redundant:
-     AllMeans = ("Travel from" | "Go from" | "Get from" | "From" );
-     Bus = ("Travel by bus from" | "Go by bus from" | "Get by bus from" | "Bus from" );
-     Train = ("Travel by train from" | "Go by train from" | "Get by train from" | "Train from" );
-     Tram = ("Travel by tram from" | "Go by tram from" | "Get by tram from" | "Tram from" );
-     Boat = ("Travel by boat from" | "Go by boat from" | "Get by boat from" | "Boat from" );

Is there some way to make it smaller and smarter?

**Comment by worldsayshi** [comment]
`public VasttrafikQuery(String from, String to, Date date, boolean departingDate, boolean useTrain, boolean useBus, boolean useTram, boolean useBoat)`

This constructor is very long. Can we represent the data in a more succinct way? I'm thinking that we can have a constructor that takes varargs and then represent the various options with an enum type. And instead of having multiple `if(!params.useTram)` statements we should iterate through the options and perhaps use some enum serialization.

**Comment by worldsayshi** [comment]
Mode and Offset is not very descriptive.

**Comment by worldsayshi** [comment]
departingDate => isDepartingDate or something similar

**Comment by worldsayshi** [comment]
Currently we have `findConnections( Location src, Location dest, VasttrafikQuery params)`. Can't we just have `findConnections(VasttrafikQuery params)`? And include Locations in the VasttrafikQuery? Although we already have `String from, String to` in the VasttrafikQuery.

Since we now pass VasttrafikQuery into the Vasttrafik rest client I think we should only store `Location`:s in the query object and not their string representations. The rest api "doesn't want to care about the string representations".

Perhaps `parseVasttrafikApi` could return the Map instead and have another method that builds the query object from it, using calls to `vasttrafikclient.getBestMatchStop`. There are probably better ways to do it.

**Comment by gossu** [comment]
fixed these problem with last commit

**Pull request merged**
